name: Rust

on:
  schedule:
    # run at 07 PST everyday
    - cron: "0 15 * * *"
  workflow_dispatch:
    inputs:
      MPIndex:
        description: "Morning Paper index"
        required: true
env:
  CARGO_TERM_COLOR: always

jobs:
  update_MP:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Run and set env
        # how to update github action environment variables
        # https://stackoverflow.com/a/57969570/14842908
        run: echo "MP_TITLE=$(cargo run --quiet)" >> $GITHUB_ENV
      - name: Check MP_rss
        run: cat morning_paper_feed.xml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # accessing environment variable https://stackoverflow.com/a/65287555/14842908
          commit_message: Add ${{ env.MP_TITLE }} to Morning Paper feed
          commit_user_name: Revive RSS Bot
          commit_user_email: reviverssbot@gmail.com
          commit_author: Revive RSS Bot <reviverssbot@gmail.com>
