name: Rust

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
    inputs:
      MPIndex:
        description: 'Morning Paper index'
        required: true
env:
  CARGO_TERM_COLOR: always

jobs:
  update_MP:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: cargo run --quiet
    - name: Check MP_rss
      run: cat morning_paper_feed.xml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
      commit_message: Update MP_rss
      
